# Generated by Django 5.1 on 2024-08-30 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100)),
                ('messge', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Join',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
                ('location', models.CharField(max_length=50)),
                ('photo', models.FileField(upload_to='')),
                ('license', models.FileField(upload_to='')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=20)),
                ('biodata', models.FileField(upload_to='')),
                ('accoundnumber', models.IntegerField()),
                ('status', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='mycart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('total_price', models.IntegerField()),
                ('delivered', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('description', models.CharField(max_length=1000)),
                ('features', models.CharField(max_length=1000)),
                ('category', models.CharField(choices=[('a', 'men'), ('b', 'women'), ('c', 'kids')], default='a', max_length=100)),
                ('pimg', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('User_Name', models.CharField(max_length=20)),
                ('User_Email', models.EmailField(max_length=254, unique=True)),
                ('UserPhone', models.IntegerField()),
                ('Password', models.CharField(max_length=20)),
                ('u_address', models.CharField(max_length=100)),
                ('u_district', models.CharField(max_length=20)),
                ('u_city', models.CharField(max_length=20)),
                ('u_pincode', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_fname', models.CharField(max_length=20)),
                ('so_lname', models.CharField(max_length=20)),
                ('so_email', models.EmailField(max_length=254)),
                ('so_phone', models.IntegerField()),
                ('so_address', models.TextField()),
                ('so_district', models.CharField(max_length=20)),
                ('so_city', models.CharField(max_length=20)),
                ('so_pincode', models.IntegerField()),
                ('add_message', models.CharField(max_length=250)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Out For Shipping', 'Out For Shipping'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Pending', max_length=150)),
                ('quantity', models.IntegerField()),
                ('total_price', models.FloatField()),
                ('payment_mode', models.CharField(max_length=150)),
                ('payment_id', models.CharField(max_length=150, null=True)),
                ('order_id', models.CharField(max_length=150)),
                ('tracking_no', models.CharField(max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.mycart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.products')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.register')),
            ],
        ),
        migrations.CreateModel(
            name='orderitem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('orderdet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.products')),
            ],
        ),
        migrations.AddField(
            model_name='mycart',
            name='products',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.products'),
        ),
        migrations.CreateModel(
            name='profilepic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propic', models.FileField(upload_to='images/profilepic')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.join')),
            ],
        ),
        migrations.CreateModel(
            name='PasswordReset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=4)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.register')),
            ],
        ),
        migrations.AddField(
            model_name='mycart',
            name='usr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.register'),
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=30)),
                ('status', models.IntegerField(default=0)),
                ('item_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.products')),
                ('user_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.register')),
            ],
        ),
    ]
